package com.codeitup_team5.dao;

import java.util.List;

import com.codeitup_team5.pojo.HealthData;


public interface HealthDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataForhealth
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    int insert(HealthData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataForhealth
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    int insertSelective(HealthData record);
   public List <HealthData> selectAllView (HealthData record);
    
}