package com.codeitup_team5.pojo;

public class HealthData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Patient_ID
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Pain_Assesment
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private String painAssesment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Pain_Scale
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer painScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Head_Headaches
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer headHeadaches;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Head_Concussion
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer headConcussion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Eyes_Blurred_Vision
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer eyesBlurredVision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Eyes_Drainage
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer eyesDrainage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Eyes_Itching
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer eyesItching;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Eyes_Pain
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer eyesPain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Ear_Pain
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer earPain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Ear_hearingaid
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer earHearingaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Respiratory_Cough
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer respiratoryCough;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Respiratory_Sputum
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer respiratorySputum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Cardiovascular_Chest_Pain
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer cardiovascularChestPain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Gastrointestinal_Headburn
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer gastrointestinalHeadburn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Gastrointestinal_Vomiting
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer gastrointestinalVomiting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataForhealth.Gastrointestinal_Constipation
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    private Integer gastrointestinalConstipation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Patient_ID
     *
     * @return the value of dataForhealth.Patient_ID
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Patient_ID
     *
     * @param patientId the value for dataForhealth.Patient_ID
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Pain_Assesment
     *
     * @return the value of dataForhealth.Pain_Assesment
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public String getPainAssesment() {
        return painAssesment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Pain_Assesment
     *
     * @param painAssesment the value for dataForhealth.Pain_Assesment
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setPainAssesment(String painAssesment) {
        this.painAssesment = painAssesment == null ? null : painAssesment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Pain_Scale
     *
     * @return the value of dataForhealth.Pain_Scale
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getPainScale() {
        return painScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Pain_Scale
     *
     * @param painScale the value for dataForhealth.Pain_Scale
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setPainScale(Integer painScale) {
        this.painScale = painScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Head_Headaches
     *
     * @return the value of dataForhealth.Head_Headaches
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getHeadHeadaches() {
        return headHeadaches;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Head_Headaches
     *
     * @param headHeadaches the value for dataForhealth.Head_Headaches
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setHeadHeadaches(Integer headHeadaches) {
        this.headHeadaches = headHeadaches;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Head_Concussion
     *
     * @return the value of dataForhealth.Head_Concussion
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getHeadConcussion() {
        return headConcussion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Head_Concussion
     *
     * @param headConcussion the value for dataForhealth.Head_Concussion
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setHeadConcussion(Integer headConcussion) {
        this.headConcussion = headConcussion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Eyes_Blurred_Vision
     *
     * @return the value of dataForhealth.Eyes_Blurred_Vision
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getEyesBlurredVision() {
        return eyesBlurredVision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Eyes_Blurred_Vision
     *
     * @param eyesBlurredVision the value for dataForhealth.Eyes_Blurred_Vision
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setEyesBlurredVision(Integer eyesBlurredVision) {
        this.eyesBlurredVision = eyesBlurredVision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Eyes_Drainage
     *
     * @return the value of dataForhealth.Eyes_Drainage
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getEyesDrainage() {
        return eyesDrainage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Eyes_Drainage
     *
     * @param eyesDrainage the value for dataForhealth.Eyes_Drainage
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setEyesDrainage(Integer eyesDrainage) {
        this.eyesDrainage = eyesDrainage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Eyes_Itching
     *
     * @return the value of dataForhealth.Eyes_Itching
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getEyesItching() {
        return eyesItching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Eyes_Itching
     *
     * @param eyesItching the value for dataForhealth.Eyes_Itching
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setEyesItching(Integer eyesItching) {
        this.eyesItching = eyesItching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Eyes_Pain
     *
     * @return the value of dataForhealth.Eyes_Pain
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getEyesPain() {
        return eyesPain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Eyes_Pain
     *
     * @param eyesPain the value for dataForhealth.Eyes_Pain
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setEyesPain(Integer eyesPain) {
        this.eyesPain = eyesPain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Ear_Pain
     *
     * @return the value of dataForhealth.Ear_Pain
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getEarPain() {
        return earPain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Ear_Pain
     *
     * @param earPain the value for dataForhealth.Ear_Pain
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setEarPain(Integer earPain) {
        this.earPain = earPain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Ear_hearingaid
     *
     * @return the value of dataForhealth.Ear_hearingaid
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getEarHearingaid() {
        return earHearingaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Ear_hearingaid
     *
     * @param earHearingaid the value for dataForhealth.Ear_hearingaid
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setEarHearingaid(Integer earHearingaid) {
        this.earHearingaid = earHearingaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Respiratory_Cough
     *
     * @return the value of dataForhealth.Respiratory_Cough
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getRespiratoryCough() {
        return respiratoryCough;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Respiratory_Cough
     *
     * @param respiratoryCough the value for dataForhealth.Respiratory_Cough
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setRespiratoryCough(Integer respiratoryCough) {
        this.respiratoryCough = respiratoryCough;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Respiratory_Sputum
     *
     * @return the value of dataForhealth.Respiratory_Sputum
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getRespiratorySputum() {
        return respiratorySputum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Respiratory_Sputum
     *
     * @param respiratorySputum the value for dataForhealth.Respiratory_Sputum
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setRespiratorySputum(Integer respiratorySputum) {
        this.respiratorySputum = respiratorySputum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Cardiovascular_Chest_Pain
     *
     * @return the value of dataForhealth.Cardiovascular_Chest_Pain
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getCardiovascularChestPain() {
        return cardiovascularChestPain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Cardiovascular_Chest_Pain
     *
     * @param cardiovascularChestPain the value for dataForhealth.Cardiovascular_Chest_Pain
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setCardiovascularChestPain(Integer cardiovascularChestPain) {
        this.cardiovascularChestPain = cardiovascularChestPain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Gastrointestinal_Headburn
     *
     * @return the value of dataForhealth.Gastrointestinal_Headburn
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getGastrointestinalHeadburn() {
        return gastrointestinalHeadburn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Gastrointestinal_Headburn
     *
     * @param gastrointestinalHeadburn the value for dataForhealth.Gastrointestinal_Headburn
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setGastrointestinalHeadburn(Integer gastrointestinalHeadburn) {
        this.gastrointestinalHeadburn = gastrointestinalHeadburn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Gastrointestinal_Vomiting
     *
     * @return the value of dataForhealth.Gastrointestinal_Vomiting
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getGastrointestinalVomiting() {
        return gastrointestinalVomiting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Gastrointestinal_Vomiting
     *
     * @param gastrointestinalVomiting the value for dataForhealth.Gastrointestinal_Vomiting
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setGastrointestinalVomiting(Integer gastrointestinalVomiting) {
        this.gastrointestinalVomiting = gastrointestinalVomiting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataForhealth.Gastrointestinal_Constipation
     *
     * @return the value of dataForhealth.Gastrointestinal_Constipation
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public Integer getGastrointestinalConstipation() {
        return gastrointestinalConstipation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataForhealth.Gastrointestinal_Constipation
     *
     * @param gastrointestinalConstipation the value for dataForhealth.Gastrointestinal_Constipation
     *
     * @mbg.generated Thu Feb 20 00:33:01 CST 2020
     */
    public void setGastrointestinalConstipation(Integer gastrointestinalConstipation) {
        this.gastrointestinalConstipation = gastrointestinalConstipation;
    }
}